// cloudflare.config.ts — cf CLI configuration for the api Worker
//
// Generated by `cf migrate` from wrangler.json. cf only discovers `cloudflare.config.ts`, hence TypeScript here.
// D1 migrations live in ./migrations, which is cf's default `--dir` for `cf d1 migrations apply`.
// The former Wrangler `production` environment is `--mode production`; the default mode is local development.

import { bindings, defineConfig } from "cf/config";

export default defineConfig((ctx) => {
  const isProduction = ctx.mode === "production";

  return {
    worker: {
      name: "waneetabeach-ca",
      compatibilityDate: "2025-05-01",
      entrypoint: "./src/index.js",
      observability: {
        enabled: false,
        headSamplingRate: 1,
        logs: {
          enabled: true,
          headSamplingRate: 1,
          persist: true,
          invocationLogs: true,
        },
        traces: {
          enabled: false,
          persist: true,
          headSamplingRate: 1,
        },
      },
      assets: {
        notFoundHandling: "404-page",
      },
      env: {
        FROM_ADDRESS: bindings.text("no-reply@waneetabeach.ca"),
        DB: bindings.d1({
          name: "waneetabeach",
          // cf d1 commands only accept IDs, so local development needs a fixed placeholder UUID rather than a name
          id: isProduction ? "380ecce7-af1b-423d-b092-02b21c8f51f8" : "00000000-0000-4000-8000-000000000001",
        }),
        EMAIL: bindings.sendEmail({
          allowedSenderAddresses: ["no-reply@waneetabeach.ca"],
        }),
        AUTH_SERVICE: bindings.worker({
          worker: "waneetabeach-auth",
        }),
      },
    },
  };
});
