// cloudflare.config.ts — cf CLI configuration for the api Worker
//
// Generated by `cf migrate` from wrangler.json. cf only discovers `cloudflare.config.ts`, hence TypeScript here.
// D1 migrations live in ./migrations, which is cf's default `--dir` for `cf d1 migrations apply`.

import { bindings, defineConfig } from "cf/config";

export default defineConfig({
  worker: {
    name: "waneetabeach-ca",
    compatibilityDate: "2025-05-01",
    entrypoint: "./src/index.js",
    assets: {
      notFoundHandling: "404-page",
    },
    env: {
      FROM_ADDRESS: bindings.text("no-reply@waneetabeach.ca"),
      DB: bindings.d1({
        name: "waneetabeach",
        id: "00000000-0000-4000-8000-000000000001",
      }),
      EMAIL: bindings.sendEmail({
        allowedSenderAddresses: ["no-reply@waneetabeach.ca"],
      }),
      AUTH_SERVICE: bindings.worker({
        worker: "waneetabeach-auth",
      }),
    },
  },
});
