// cloudflare.config.ts — cf CLI configuration for the auth Worker
//
// Generated by `cf migrate` from wrangler.json. cf only discovers `cloudflare.config.ts`, hence TypeScript here.
// D1 migrations live in ./migrations, which is cf's default `--dir` for `cf d1 migrations apply`.
// AUTH_SECRET value comes from .dev.vars locally and `secret put` in production; only its presence is declared here.

import { bindings, defineConfig } from "cf/config";

export default defineConfig({
  worker: {
    name: "waneetabeach-auth",
    compatibilityDate: "2025-05-01",
    compatibilityFlags: ["nodejs_compat"],
    entrypoint: "./src/index.js",
    env: {
      BASE_URL: bindings.text("http://localhost:8787"),
      AUTH_SECRET: bindings.secret(),
      AUTH_DB: bindings.d1({
        name: "waneetabeach-auth",
        id: "local-dev-placeholder",
      }),
    },
  },
});
