// cloudflare.config.ts — cf CLI configuration for the auth Worker
//
// Generated by `cf migrate` from wrangler.json. cf only discovers `cloudflare.config.ts`, hence TypeScript here.
// D1 migrations live in ./migrations, which is cf's default `--dir` for `cf d1 migrations apply`.
// The former Wrangler `production` environment is `--mode production`; the default mode is local development.
// AUTH_SECRET value comes from .dev.vars locally and `cf workers secrets update` in production; only its presence is declared here.

import { bindings, defineConfig } from "cf/config";

export default defineConfig((ctx) => {
  const isProduction = ctx.mode === "production";

  return {
    worker: {
      name: "waneetabeach-auth",
      compatibilityDate: "2025-05-01",
      compatibilityFlags: ["nodejs_compat"],
      entrypoint: "./src/index.js",
      observability: {
        enabled: true,
        headSamplingRate: 1,
        logs: {
          enabled: true,
          headSamplingRate: 1,
          persist: true,
          invocationLogs: true,
        },
        traces: {
          enabled: false,
          persist: true,
          headSamplingRate: 1,
        },
      },
      env: {
        BASE_URL: bindings.text(isProduction ? "https://waneetabeach.ca" : "http://localhost:8787"),
        AUTH_SECRET: bindings.secret(),
        AUTH_DB: bindings.d1({
          name: "waneetabeach-auth",
          // cf d1 commands only accept IDs, so local development needs a fixed placeholder UUID rather than a name
          id: isProduction ? "493bbb5a-9da4-4baa-bf8f-09c037902386" : "00000000-0000-4000-8000-000000000002",
        }),
        EMAIL: bindings.sendEmail({
          allowedSenderAddresses: ["no-reply@waneetabeach.ca"],
        }),
      },
    },
  };
});
